id: twitter_packed # wijzig dit in de id die je voor deze crawl wil gebruiken, bv. 20201202_twitter_packed
ignore_robots: true
max_claimed_sites: 1
time_limit: 3600 # tijdslimiet om een infinite crawl te vermijden
warcprox_meta:
  # warc-prefix bepaalt de prefix van de bestandsnaam
  warc-prefix: 20220201_twitter_packed # wijzig dit naar naam van keuze, bv. 20201202_twitter_packed
  stats:
    buckets:
      - twitter_packed_stats # wijzig id in de id die je in de eerste regel gegeven hebt

scope:
  accepts:
    - ssurt: com,twitter,www,//https:/PACKEDvzw
    - ssurt: com,twimg,pbs//https:/media

seeds:
  # wijzig in onderstaande URL's twitter-user in de naam van de twitter-gebruiker/stream, bv. PACKEDvzw
  - url: https://twitter.com/packedvzw # Twitter timeline
  - url: https://twitter.com/packedvzw/with_replies # pagina met ook alle replies
